[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "cd backend && python -m pip install --upgrade pip",
  "cd backend && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python manage.py migrate && uvicorn spotter.asgi:application --host 0.0.0.0 --port $PORT"
